import { Goal, Task } from "./types";

export const NewTaskInitial: Task = {
  activity: [],
  added_at: "",
  added_by_uid: "",
  assigned_to: [],
  attachments: [],
  comments: [],
  completed_at: "",
  content: "",
  date_set: {
    date_iso: "",
    time_from: "",
    time_to: "",
    with_time: false,
  },
  description: "",
  done: false,
  is_archived: false,
  labels: [],
  priority: 0,
  project_id: "",
  reminder_date: "",
  seconds_planned: 0,
  seconds_spent: 0,
  section_id: "",
  subtasks: [],
  task_id: "",
  task_order: 0,
  updated_at: "",
  working_on: false,
  is_recurring: false,
  recurring: {
    recurring_end: "",
    recurring_id: "",
    recurring_number: 1,
    recurring_option: "",
    recurring_start: "",
  },
};

export const NewGoalInitial: Goal = {
  activity: [],
  added_at: "",
  added_by_uid: "",
  assigned_to: [],
  attachments: [],
  comments: [],
  completed_at: "",
  content: "",
  date_set: {
    date_iso: "",
    time_from: "",
    time_to: "",
    with_time: false,
  },
  description: "",
  done: false,
  is_archived: false,
  labels: [],
  days_spent: 0,
  priority: 0,
  project_id: "",
  reminder_date: "",
  section_id: "",
  subtasks: [],
  goal_id: "",
  goal_order: 0,
  updated_at: "",
  working_on: false,
};
